#  nomes de variaveis de TABLE's para a API

DATABASE_NAME="packDeliv_DB"

COMPANY= 'Empresa'
DELIVERYMAN= 'Entregador'
ADRESS= 'Endereco'
VEHICLE='Veiculo'
SERVICE_ORDER='Ordem_de_servico'
DELIVERY='Entrega'
PACKAGE='Pacote'
LOCALIZATION="Localizacao"
CLIENT="Cliente"

CLIENT_ID='Id'
CLIENT_UPI='CPF'#unique client identifier
CLIENT_NAME='Nome'
ADRESSES='Enderecos'


COMPANY_ID = 'Id'        
COMPANY_ID_ADRESS ='Id_endereco'
COMPANY_NAME='Nome_fantasia'
COMPANY_PASSWORD ='Senha'
COMPANY_LOGIN ='Login'
COMPANY_EMAIL ='Email' 
COMPANY_UCI= 'CNPJ' # unique identifier of company
COMPANY_TYPE= 'Tipo'

DELIVERYMAN_ID= 'id'
DELIVERYMAN_ID_VEHICLE= 'Id_veiculo'
DELIVERYMAN_ID_COMPANY = 'id_empresa'
DELIVERYMAN_NAME='Nome'
DELIVERYMAN_STATUS='Status'
DELIVERYMAN_DUI= 'CNH' #driver unique identifier
DELIVERYMAN_AVAILABILITY= 'Disponibilidade'
DELIVERYMAN_READY= 'Apto'
DELIVERYMAN_LOCALIZATION= 'Localizacao'

ADRESS_ID= 'Id'
ADRESS_STREET= 'Logradouro'
ADRESS_NUMBER= 'Numero'
ADRESS_COMPLEMENT= 'Complemento'
ADRESS_DISTRICT= 'Bairro'
ADRESS_POSTAL_CODE = 'CEP'
ADRESS_CITY= 'Cidade'
ADRESS_STATE= 'Estado'
ADRESS_COUNTRY= 'Pais'
ADRESS_TYPE= 'Tipo'

ADRESS_COMPANY_MATRIX='endereco_empresa_matriz'
ADRESS_COMPANY='endereco_empresa'
ADRESS_CLIENT='endereco_cliente'

VEHICLE_ID= 'id'
VEHICLE_LICENSE_PLATE= 'placa'
VEHICLE_YEAR = 'ano'
VEHICLE_MODEL = 'modelo'
VEHICLE_COLOR = 'cor'
VEHICLE_READY= 'apto'
VEHICLE_VOLUME= 'volume'


SERVICE_ORDER_ID='Id'
SERVICE_ORDER_IDENTIFIER_CODE='Codigo'
SERVICE_ORDER_SHIPPING_DATE= 'Data_expedicao'
SERVICE_ORDER_FINALIZATION_DATE='Data_finalizacao'
DELIVERIES='Entregas'

DELIVERY_ID='Id'
DELIVERY_IDENTIFIER_CODE='codigo'
DELIVERY_SHIPPING_DATE='Data_expedicao'
DELIVERY_FINALIZATION_DATE='Data_finalizacao'
DELIVERY_ID_SERVICE_ORDER='Id_ordem_de_servico'
DELIVERY_ID_PACKAGE='Id_pacote Varchar'
DELIVERY_ID_SUCESS='Sucesso'
DELIVERY_STATUS='Status'
DELIVERY_TYPE='Tipo'

PACKAGE_ID='Id'
PACKAGE_WIDTH='Largura'
PACKAGE_HEIGHT='Altura'
PACKAGE_LENGTH='Comprimento'
PACKAGE_WEIGHT='Peso'
PACKAGE_SHIPPED='Expedido'
PACKAGE_RECEIVED='Recebido'
PACKAGE_ID_ADRESS_START ='Id_endereco_inicio'
PACKAGE_ID_ADRESS_DESTINY ='Id_endereco_destino'
PACKAGE_CURRENT_STATIC_LOCATION='Local_atual_estatico'
PACKAGE_VOLUME="volume"

LOCALIZATION_ID="Id"
LOCALIZATION_LAT="Lat"
LOCALIZATION_LONG="Long"
LOCALIZATION_TYPE="Tipo"

LOCALIZATION_ADRESS="localizacao_endereco"
LOCALIZATION_DELIVERYMAN="localizacao_entregador"











