#  nomes de variaveis de TABLE's para a API

DATABASE_NAME="packDeliv_DB"

TABLE_COMPANY= 'Empresa'
TABLE_DELIVERYMAN= 'Entregador'
TABLE_ADRESS= 'Endereco'
TABLE_VEHICLE='Veiculo'
TABLE_SERVICE_ORDER='Ordem_de_servico'
TABLE_DELIVERY='Entrega'
TABLE_PACKAGE='Pacote'


TABLE_COMPANY_ID = 'id'        
TABLE_COMPANY_ID_ADRESS ='Id_endereco'
TABLE_COMPANY_NAME='Nome_fantasia'
TABLE_COMPANY_PASSWORD ='Senha'
TABLE_COMPANY_LOGIN ='Login'
TABLE_COMPANY_EMAIL ='Email' 
TABLE_COMPANY_UCI= 'CNPJ' # unique identifier of company

TABLE_DELIVERYMAN_ID= 'id'
TABLE_DELIVERYMAN_ID_VEHICLE= 'Id_veiculo'
TABLE_DELIVERYMAN_ID_COMPANY = 'id_empresa'
TABLE_DELIVERYMAN_DUI= 'cnh' #driver unique identifier
TABLE_DELIVERYMAN_AVAILABILITY= 'Disponibilidade'
TABLE_DELIVERYMAN_READY= 'apto'
TABLE_DELIVERYMAN_LOCALIZATION= 'localizacao'

TABLE_ADRESS_ID= 'Id'
TABLE_ADRESS_STREET= 'Logradouro'
TABLE_ADRESS_NUMBER= 'Numero'
TABLE_ADRESS_COMPLEMENT= 'Complemento'
TABLE_ADRESS_DISTRICT= 'Bairro'
TABLE_ADRESS_POSTAL_CODE = 'CEP'
TABLE_ADRESS_CITY= 'Cidade'
TABLE_ADRESS_STATE= 'Estado'
TABLE_ADRESS_COUNTRY= 'Pais'

TABLE_VEHICLE_ID= 'id'
TABLE_VEHICLE_LICENSE_PLATE= 'placa'
TABLE_VEHICLE_YEAR = 'ano'
TABLE_VEHICLE_MODEL = 'modelo'
TABLE_VEHICLE_COLOR = 'cor'
TABLE_VEHICLE_READY= 'apto'

TABLE_SERVICE_ORDER_ID='Id'
TABLE_SERVICE_ORDER_IDENTIFIER_CODE='Codigo'
TABLE_SERVICE_ORDER_SHIPPING_DATE= 'Data_expedicao'
TABLE_SERVICE_ORDER_FINALIZATION_DATE='Data_finalizacao'

TABLE_DELIVERY_ID='Id'
TABLE_DELIVERY_IDENTIFIER_CODE='codigo'
TABLE_DELIVERY_SHIPPING_DATE='Data_expedicao'
TABLE_DELIVERY_FINALIZATION_DATE='Data_finalizacao'
TABLE_DELIVERY_ID_SERVICE_ORDER='Id_ordem_de_servico'
TABLE_DELIVERY_ID_PACKAGE='Id_pacote Varchar'
TABLE_DELIVERY_ID_SUCESS='Sucesso'

TABLE_PACKAGE_ID='Id'
TABLE_PACKAGE_WIDTH='Largura'
TABLE_PACKAGE_HEIGHT='Altura'
TABLE_PACKAGE_LENGTH='Comprimento'
TABLE_PACKAGE_WEIGHT='Peso'
TABLE_PACKAGE_SHIPPED='Expedido'
TABLE_PACKAGE_RECEIVED='Recebido'
TABLE_PACKAGE_LOCAL_DESTINY='Destino'
TABLE_PACKAGE_ID_ADRESS ='Id_endereco'
TABLE_PACKAGE_CURRENT_STATIC_LOCATION='Local_atual_estatico'












